use anyhow::Result;
use serde::{Deserialize, Serialize};
use sysinfo::{System, ProcessesToUpdate};
use std::fs::{self, OpenOptions};
use std::io::{Read, Write};

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct Policy {
    pub policy_type: String,
    pub target: String,
    pub action: String,
    pub reason: String,
    pub config_json: String,
}

#[derive(Deserialize, Debug)]
struct AppConfig {
    match_type: Option<String>,
}

#[derive(Deserialize, Debug)]
struct WebConfig {
    domains: Option<Vec<String>>,
}

pub fn enforce_active_policies(policies: &[Policy]) {
    let mut sys = System::new();
    sys.refresh_processes(ProcessesToUpdate::All);

    // 1. App Control (Bloqueio de Aplicações)
    let app_policies: Vec<&Policy> = policies.iter().filter(|p| p.policy_type == "app").collect();
    for policy in app_policies {
        if policy.action != "block" { continue; }
        
        let config: AppConfig = serde_json::from_str(&policy.config_json)
            .unwrap_or(AppConfig { match_type: Some("name".to_string()) });
            
        let target = policy.target.to_lowercase();
        let match_type = config.match_type.unwrap_or_else(|| "name".to_string());

        for (_pid, process) in sys.processes() {
            let name = process.name().to_string_lossy().to_lowercase();
            let path = process.exe().unwrap_or(std::path::Path::new("")).to_string_lossy().to_lowercase();

            let is_match = match match_type.as_str() {
                "path" => path.contains(&target),
                _ => name.contains(&target) || path.contains(&target), // Apanha "fraps.exe" ou "fraps"
            };

            if is_match {
                println!("[Enforcer] A terminar aplicação proibida: {}", name);
                process.kill(); // Termina imediatamente
            }
        }
    }

    // 2. Web Filtering (Bloqueio de Sites via Hosts File)
    let web_policies: Vec<&Policy> = policies.iter().filter(|p| p.policy_type == "web").collect();
    let _ = enforce_hosts_file(&web_policies);
}

// Manipula o ficheiro hosts do Windows de forma segura
fn enforce_hosts_file(policies: &[&Policy]) -> Result<()> {
    let hosts_path = r"C:\Windows\System32\drivers\etc\hosts";
    let mut current_content = String::new();
    
    if let Ok(mut file) = fs::File::open(hosts_path) {
        file.read_to_string(&mut current_content).ok();
    }

    // Remove apenas as regras antigas do AssetScan para limpar a cache
    let mut lines: Vec<&str> = current_content.lines().filter(|l| !l.contains("# ASSETSCAN")).collect();
    let mut new_lines = Vec::new();

    for policy in policies {
        if policy.action != "block" { continue; }
        if let Ok(config) = serde_json::from_str::<WebConfig>(&policy.config_json) {
            if let Some(domains) = config.domains {
                for domain in domains {
                    let clean_domain = domain.trim();
                    if !clean_domain.is_empty() {
                        new_lines.push(format!("127.0.0.1 {} # ASSETSCAN", clean_domain));
                        new_lines.push(format!("127.0.0.1 www.{} # ASSETSCAN", clean_domain));
                    }
                }
            }
        }
    }

    if !new_lines.is_empty() {
        lines.push("# ASSETSCAN AUTOGENERATED");
        lines.extend(new_lines.iter().map(|s| s.as_str()));
    }

    let final_content = lines.join("\n") + "\n";
    if let Ok(mut file) = OpenOptions::new().write(true).truncate(true).open(hosts_path) {
        file.write_all(final_content.as_bytes()).ok();
    }

    Ok(())
}